import {randomBytes,createHash} from 'node:crypto';
import {createRemoteJWKSet,jwtVerify} from 'jose';
const sha=x=>createHash('sha256').update(x).digest('hex');
export function installOidc(app,pool,audit){
 const ready=()=>process.env.IDENTITY_PROVIDER!=='bdms' && !!(process.env.OIDC_ISSUER&&process.env.OIDC_CLIENT_ID&&process.env.OIDC_CLIENT_SECRET&&process.env.OIDC_REDIRECT_URI);
 const pending=new Map();let discovery;
 async function metadata(){if(discovery)return discovery;const issuer=process.env.OIDC_ISSUER.replace(/\/$/,'');const r=await fetch(issuer+'/.well-known/openid-configuration',{signal:AbortSignal.timeout(10000)});if(!r.ok)throw new Error('Company identity-provider discovery failed.');discovery=await r.json();if(discovery.issuer.replace(/\/$/,'')!==issuer)throw new Error('Identity-provider issuer mismatch.');return discovery;}
 app.get('/api/auth/methods',(req,res)=>res.json({local:process.env.IDENTITY_PROVIDER!=='bdms',bdms:process.env.IDENTITY_PROVIDER==='bdms',sso:ready()}));
 app.get('/api/auth/sso',async(req,res)=>{if(!ready())return res.status(503).json({error:'Company SSO is not configured.'});const m=await metadata();const state=randomBytes(24).toString('hex'),nonce=randomBytes(24).toString('hex'),verifier=randomBytes(32).toString('base64url');pending.set(state,{nonce,verifier,expires:Date.now()+600000});for(const [k,v]of pending)if(v.expires<Date.now())pending.delete(k);res.cookie('tt_oidc_state',state,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',maxAge:600000,path:'/'});const url=new URL(m.authorization_endpoint);url.search=new URLSearchParams({client_id:process.env.OIDC_CLIENT_ID,response_type:'code',scope:'openid email profile',redirect_uri:process.env.OIDC_REDIRECT_URI,state,nonce,code_challenge:createHash('sha256').update(verifier).digest('base64url'),code_challenge_method:'S256'}).toString();res.redirect(url.toString());});
 app.get('/api/auth/callback',async(req,res)=>{if(process.env.IDENTITY_PROVIDER==='bdms')return res.sendStatus(403);const state=String(req.query.state||'');const flow=pending.get(state);const stateCookie=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('tt_oidc_state='))?.slice(14);pending.delete(state);res.clearCookie('tt_oidc_state');if(!flow||flow.expires<Date.now()||stateCookie!==state)return res.status(400).send('Sign-in state expired or did not match. Please start sign-in again.');if(!req.query.code)return res.status(400).send('Company sign-in did not return an authorization code.');const m=await metadata();const response=await fetch(m.token_endpoint,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'authorization_code',code:String(req.query.code),redirect_uri:process.env.OIDC_REDIRECT_URI,client_id:process.env.OIDC_CLIENT_ID,client_secret:process.env.OIDC_CLIENT_SECRET,code_verifier:flow.verifier}),signal:AbortSignal.timeout(15000)});if(!response.ok)return res.status(401).send('Company sign-in failed.');const tokens=await response.json();if(!tokens.id_token)return res.status(401).send('The identity provider did not return an ID token.');const {payload}=await jwtVerify(tokens.id_token,createRemoteJWKSet(new URL(m.jwks_uri)),{issuer:m.issuer,audience:process.env.OIDC_CLIENT_ID});if(payload.nonce!==flow.nonce||!payload.email||payload.email_verified===false)return res.status(401).send('Identity verification failed.');const user=(await pool.query('SELECT * FROM users WHERE lower(email)=lower($1) AND active=true',[payload.email])).rows[0];if(!user)return res.status(403).send('Your company account has not been assigned access to this workspace. Ask the administrator to add it.');const token=randomBytes(32).toString('hex');await pool.query("INSERT INTO sessions(token_hash,user_id,expires_at) VALUES($1,$2,now()+interval '12 hours')",[sha(token),user.id]);res.cookie('tt_session',token,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'strict',maxAge:43200000,path:'/'});await audit(pool,user,null,'Company SSO signed in','session',{},{});res.redirect('/#/dashboard');});
 return ready;
}
