import {importCell} from './tender-import.mjs';
import {tenderAllowed,tenderCanList,tenderAdministration} from './src/tender-permissions.mjs';
import {bdmsEnabled,identityRequest,projectIdentity,syncDirectory} from './auth-bdms.mjs';
import 'dotenv/config';
import express from 'express';
import {installOidc} from './auth-oidc.mjs';
import {installPortalImport} from './portal-import.mjs';
import compression from 'compression';
import multer from 'multer';
import ExcelJS from 'exceljs';
import {readFormImport} from './form-import.mjs';
import nodemailer from 'nodemailer';
import {randomUUID,randomBytes,createHash,scryptSync,timingSafeEqual} from 'node:crypto';
import {promises as fs,existsSync} from 'node:fs';
import path from 'node:path';
import {runtimeConfig} from './runtime-config.mjs';
import {pool,transaction,settings,audit,hashPassword,embedded,localDir} from './db.mjs';
import {ROLES,MODULES,DEFAULT_SETTINGS,permitted,canSeePricing,pricingFields,classify,scorecard,deadlineUtc} from './src/domain.mjs';
const runtime=runtimeConfig();
const app=express();app.disable('x-powered-by');if(runtime.production)app.set('trust proxy',1);app.use(compression());app.use(express.json({limit:'5mb'}));
const PORT=Number(process.env.PORT||4310);const spec=JSON.parse(await fs.readFile('src/workbook.json','utf8'));
const fileRoot=runtime.documentsDir;await fs.mkdir(fileRoot,{recursive:true});
const restoreUpload=multer({storage:multer.memoryStorage(),limits:{fileSize:512*1024*1024,files:1}});
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:30*1024*1024,files:1}});
const tenderInput=raw=>Object.fromEntries(Object.entries(raw||{}).filter(([k])=>spec.fields.some(f=>f.key===k&&!f.computed&&!['approvedBy','decisionDate'].includes(k))||['timezone','noGoReason'].includes(k)));
const sha=x=>createHash('sha256').update(x).digest('hex');const fail=(status,message)=>Object.assign(new Error(message),{status});
const cleanUser=u=>({id:u.id,name:u.name,email:u.bdms_id?(u.contact_email||''):u.email,roles:u.roles,businessUnit:u.business_unit,active:u.active,phone:u.phone,bdmsId:u.bdms_id,login:u.bdms_login,tenderPermissions:u.tender_permissions});
function sessionDetails(req){return {ipAddress:req.ip,deviceId:String(req.headers['x-device-id']||'').slice(0,80),userAgent:String(req.headers['user-agent']||'').slice(0,500)};}
function cookie(req){return (req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('tt_session='))?.slice(11);}
const attempts=new Map();
const ssoReady=installOidc(app,pool,audit);
app.use('/api',(req,res,next)=>{res.set('Cache-Control','no-store');if(['POST','PUT','PATCH','DELETE'].includes(req.method)&&req.headers.origin){const origin=new URL(req.headers.origin);if(runtime.production?origin.origin!==runtime.publicOrigin:origin.host!==req.headers.host)return next(fail(403,'Request origin is not allowed.'));}next();});
app.get('/api/health',async(req,res)=>{const r=await pool.query('SELECT version()');res.json({status:'ok',database:'PostgreSQL',version:r.rows[0].version,serverTime:new Date().toISOString()});});
app.post('/api/login',async(req,res)=>{const ip=req.ip;const attempt=attempts.get(ip)||{count:0,start:Date.now()};if(Date.now()-attempt.start>900000){attempt.count=0;attempt.start=Date.now();}if(++attempt.count>30)throw fail(429,'Too many sign-in attempts. Try again in 15 minutes.');attempts.set(ip,attempt);let profile;let u;if(bdmsEnabled()){profile=await identityRequest('authenticate',{username:req.body.username||req.body.email,password:req.body.password,details:sessionDetails(req)});u=await projectIdentity(pool,profile);}else{u=(await pool.query('SELECT * FROM users WHERE lower(email)=lower($1) AND active=true',[String(req.body.email||'')])).rows[0];if(!u)throw fail(401,'Email or password is incorrect.');const [salt,hash]=u.password_hash.split(':');const input=scryptSync(String(req.body.password||''),salt,64);if(!timingSafeEqual(input,Buffer.from(hash,'hex')))throw fail(401,'Email or password is incorrect.');}attempts.delete(ip);const token=randomBytes(32).toString('hex');await pool.query("INSERT INTO sessions(token_hash,user_id,expires_at,credential_version,bdms_session_id) VALUES($1,$2,now()+interval '30 days',$3,$4)",[sha(token),u.id,profile?.credentialVersion||null,profile?.sessionId||null]);res.cookie('tt_session',token,{httpOnly:true,sameSite:'strict',maxAge:2592000000,secure:runtime.production,path:'/'});await audit(pool,u,null,'Signed in','session',{},{});res.json(cleanUser(u));});
app.use('/api',async(req,res,next)=>{if(['/health','/login','/logout'].includes(req.path))return next();const token=cookie(req);if(!token)return next(fail(401,'Please sign in.'));const r=await pool.query('SELECT u.*,s.credential_version,s.bdms_session_id FROM sessions s JOIN users u ON u.id=s.user_id WHERE token_hash=$1 AND expires_at>now() AND u.active=true',[sha(token)]);if(!r.rowCount)return next(fail(401,'Your session has expired.'));let user=r.rows[0];if(bdmsEnabled()){if(!user.bdms_id||!user.credential_version||!user.bdms_session_id)throw fail(401,'Please sign in with your BDMS account.');try{const profile=await identityRequest('validate',{id:user.bdms_id,credentialVersion:user.credential_version,sessionId:user.bdms_session_id,details:sessionDetails(req)});req.bdmsSession={id:user.bdms_id,credentialVersion:user.credential_version,sessionId:user.bdms_session_id};user=await projectIdentity(pool,profile);}catch(error){if([401,403].includes(error.status)){await pool.query('DELETE FROM sessions WHERE token_hash=$1',[sha(token)]);error.status=401;}throw error;}}req.user={...cleanUser(user),permissionView:req.headers['x-mobile']==='true'?'mobile':'desktop'};req.settings=await settings();next();});
app.use('/api',(req,res,next)=>{const p=req.path;if(p.startsWith('/admin/')&&!req.user.roles.includes('System Administrator'))return next(fail(403,'Administrator access required.'));if(!req.user?.tenderPermissions)return next();let key=null;if(p.startsWith('/admin/')){const section=p.split('/')[2];key='admin.'+({deliveries:'integrations','run-reminders':'integrations',restore:'backup',settings:'workflow'}[section]||section);if(section==='settings'){const changed=Object.keys(req.body||{}).filter(k=>JSON.stringify(req.body[k])!==JSON.stringify(req.settings[k]));if(changed.some(k=>k==='permissions'||k==='approvers')&&!tenderAllowed(req.user,'admin.access'))return next(fail(403,'Tender permission settings are restricted.'));if(changed.some(k=>!['permissions','approvers'].includes(k))&&!tenderAllowed(req.user,'admin.workflow'))return next(fail(403,'Tender workflow settings are restricted.'));return next();}}else if(p.startsWith('/import')){if(!permitted(req.user,'overview','write',req.settings))return next(fail(403,'Tender creation access required.'));}else if(p.startsWith('/portal'))key='menu.portal';else if(p.startsWith('/notifications'))key='menu.notifications';else if(p.startsWith('/approvals'))key='menu.approvals';else if(p.startsWith('/documents'))key='documents.read';else if(p==='/audit')key=req.query.tenderId?'audit.read':'admin.audit';if(key&&!tenderAllowed(req.user,key))return next(fail(403,'This Tender feature is not assigned to your BDMS user.'));if((p==='/tenders'||p==='/export'||(/^\/tenders\/[^/]+$/.test(p)&&req.method==='GET'))&&!tenderCanList(req.user))return next(fail(403,'Tender record access is not assigned.'));next();});
const isAdmin=req=>req.user.roles.includes('System Administrator')&&tenderAdministration(req.user);
const guard=(req,module,action='write')=>{if(!permitted(req.user,module,action,req.settings))throw fail(403,'Your role does not have permission for this action.');};
function sanitizeRecord(req,r){const copy=structuredClone(r);if(!canSeePricing(req.user)||(!req.user.tenderPermissions&&req.headers['x-mobile']==='true'))for(const k of pricingFields)delete copy.data[k];return copy;}
function sanitizeAudit(req,row){const copy=structuredClone(row);if(!canSeePricing(req.user)||(!req.user.tenderPermissions&&req.headers['x-mobile']==='true'))for(const k of pricingFields)delete copy.changes?.[k];return copy;}
async function getTender(req,id,c=pool,lock=false){const r=await c.query(`SELECT * FROM tenders WHERE id=$1 ${lock?'FOR UPDATE':''}`,[id]);if(!r.rowCount)throw fail(404,'Tender was not found.');const t=r.rows[0];if(t.draft&&t.creator!==req.user.id&&!isAdmin(req))throw fail(403,'Drafts are private to their creator.');if(req.user.businessUnit&&t.data.businessUnit!==req.user.businessUnit&&(!isAdmin(req)||req.user.tenderPermissions))throw fail(403,'This tender belongs to another business unit.');return t;}
async function recordsFor(id,c=pool){const records=(await c.query('SELECT * FROM records WHERE tender_id=$1 ORDER BY created_at',[id])).rows;const docs=(await c.query('SELECT * FROM documents WHERE tender_id=$1 ORDER BY type,version DESC',[id])).rows;return {records,documents:docs,calcRecords:[...records,...docs.map(d=>({module:'documents',data:{type:d.type}}))]};}
function visibleTender(req,t){if(!req.user.tenderPermissions||tenderAllowed(req.user,'overview','read'))return t;const allowed=['title','client','sector','businessUnit','owner','priority','deadline','submissionTime','timezone','currency','region','location'];return {...t,data:Object.fromEntries(Object.entries(t.data).filter(([key])=>allowed.includes(key)))};}
async function listTenders(req){const all=(await pool.query('SELECT * FROM tenders ORDER BY updated_at DESC')).rows.filter(t=>(!t.draft||t.creator===req.user.id||isAdmin(req))&&(!req.user.businessUnit||(isAdmin(req)&&!req.user.tenderPermissions)||t.data.businessUnit===req.user.businessUnit));const ids=all.map(t=>t.id);const allRecords=(await pool.query('SELECT tender_id,module,data FROM records WHERE tender_id=ANY($1::uuid[])',[ids])).rows;const docs=(await pool.query('SELECT tender_id,type FROM documents WHERE tender_id=ANY($1::uuid[])',[ids])).rows;const recordsByTender=new Map(),docsByTender=new Map();for(const r of allRecords){if(!recordsByTender.has(r.tender_id))recordsByTender.set(r.tender_id,[]);recordsByTender.get(r.tender_id).push(r);}for(const d of docs){if(!docsByTender.has(d.tender_id))docsByTender.set(d.tender_id,[]);docsByTender.get(d.tender_id).push({module:'documents',data:{type:d.type}});}return all.map(t=>{const records=recordsByTender.get(t.id)||[];return {...visibleTender(req,t),calculated:classify(t,[...records,...(docsByTender.get(t.id)||[])],req.settings),submission:tenderAllowed(req.user,'submission','read')?sanitizeRecord(req,{data:records.find(r=>r.module==='submission')?.data||{}}).data:{},evaluation:tenderAllowed(req.user,'evaluation','read')?sanitizeRecord(req,{data:records.find(r=>r.module==='evaluation')?.data||{}}).data:{},award:tenderAllowed(req.user,'award','read')?records.find(r=>r.module==='award')?.data||{}:{}};});}
app.get('/api/session/messages',async(req,res)=>{const profile=req.bdmsSession?await identityRequest('messages',{...req.bdmsSession,details:sessionDetails(req)}):{};res.json({messages:profile.messages||[]});});
app.post('/api/session/messages/:id/dismiss',async(req,res)=>{if(req.bdmsSession)await identityRequest('dismiss',{...req.bdmsSession,messageId:req.params.id,details:sessionDetails(req)});res.json({ok:true});});
app.get('/api/me',(req,res)=>res.json(req.user));
app.post('/api/logout',async(req,res)=>{const tokenHash=sha(cookie(req)||'');const row=(await pool.query('SELECT u.*,s.credential_version,s.bdms_session_id FROM sessions s JOIN users u ON u.id=s.user_id WHERE token_hash=$1',[tokenHash])).rows[0];if(bdmsEnabled()&&row?.bdms_session_id){try{await identityRequest('logout',{id:row.bdms_id,credentialVersion:row.credential_version,sessionId:row.bdms_session_id,details:sessionDetails(req)});}catch(error){console.error('BDMS logout could not be recorded:',error.message);}}await pool.query('DELETE FROM sessions WHERE token_hash=$1',[tokenHash]);res.clearCookie('tt_session',{httpOnly:true,sameSite:'strict',secure:runtime.production,path:'/'});if(row)await audit(pool,cleanUser(row),null,'Signed out','session',{},{});res.json({ok:true});});
app.post('/api/password',async(req,res)=>{if(bdmsEnabled())throw fail(403,'Change your password in BDMS.');if(String(req.body.password||'').length<10)throw fail(400,'Use at least 10 characters.');await pool.query('UPDATE users SET password_hash=$1 WHERE id=$2',[hashPassword(req.body.password),req.user.id]);res.json({ok:true});});
app.get('/api/bootstrap',async(req,res)=>{if(bdmsEnabled())await syncDirectory(pool);const masters=(await pool.query('SELECT * FROM masters ORDER BY list,value')).rows;const users=(await pool.query('SELECT id,name,email,roles,business_unit,active,phone,bdms_id,bdms_login,contact_email,tender_permissions FROM users ORDER BY name')).rows.map(cleanUser);res.json({identityProvider:bdmsEnabled()?'bdms':'local',userManagementUrl:process.env.BDMS_IDENTITY_URL||'',user:req.user,masters,users,settings:req.settings,roles:ROLES,fields:spec.fields,documents:spec.documents,modules:MODULES,serverTime:new Date().toISOString(),integrationStatus:{sso:ssoReady(),email:!!process.env.SMTP_HOST,whatsapp:!!process.env.WHATSAPP_TOKEN,portal:'Manual import',storage:fileRoot},sourceNote:'Score weights and detailed role permissions are configurable defaults. The referenced roadmap workbook was not supplied.'});});
app.get('/api/tenders',async(req,res)=>res.json(await listTenders(req)));
app.get('/api/tenders/:id',async(req,res)=>{const t=await getTender(req,req.params.id);const r=await recordsFor(t.id);const approvals=(await pool.query('SELECT a.*,u.name AS requested_by_name,d.name AS decided_by_name FROM approvals a LEFT JOIN users u ON u.id=a.requested_by LEFT JOIN users d ON d.id=a.decided_by WHERE tender_id=$1 ORDER BY a.created_at DESC',[t.id])).rows;res.json({...visibleTender(req,t),calculated:classify(t,r.calcRecords,req.settings),records:r.records.filter(x=>tenderAllowed(req.user,x.module,'read')).map(x=>sanitizeRecord(req,x)),documents:(tenderAllowed(req.user,'documents','read')?r.documents:[]).map(({stored_path,...d})=>d),approvals:tenderAllowed(req.user,'menu.approvals')?approvals:[],pricingAllowed:canSeePricing(req.user)&&(!!req.user.tenderPermissions||req.headers['x-mobile']!=='true')});});
async function validateTender(data,register,req,c=pool,id=null){if(req.user.tenderPermissions&&req.user.businessUnit&&data.businessUnit!==req.user.businessUnit)throw fail(403,'Create and edit tenders only in your assigned business unit.');const errors={};if(!/^TND-\d{4}-\d{4,}$/.test(data.tenderId||''))errors.tenderId='Use TND-YYYY-NNNN, e.g. TND-2026-0001.';if(register)for(const key of req.settings.requiredRegistrationFields)if(data[key]===undefined||data[key]===null||String(data[key]).trim()==='')errors[key]='This field is required.';
 for(const field of spec.fields){const value=data[field.key];if(value===undefined||value===null||value==='')continue;if(field.type==='number'&&(!Number.isFinite(Number(value))||Number(value)<0))errors[field.key]='Enter a non-negative number.';if(field.type==='date'&&!/^\d{4}-\d{2}-\d{2}$/.test(value))errors[field.key]='Enter a valid date.';if(field.list){const found=await c.query('SELECT 1 FROM masters WHERE list=$1 AND code=$2 AND (active=true OR EXISTS(SELECT 1 FROM tenders WHERE id=$3 AND data->>$4=$2))',[field.list,value,id,field.key]);if(!found.rowCount)errors[field.key]='Choose an active master value.';}}
 if(data.pipelineStatus==='Go - Moved to Bid Preparation'&&data.goDecision!=='Go')errors.pipelineStatus='An approved Go decision is required for this stage.';if(data.pipelineStatus==='No-Go - Dropped'&&data.goDecision!=='No-Go')errors.pipelineStatus='An approved No-Go decision is required for this stage.';if(data.deadline&&data.publishDate&&data.deadline<data.publishDate)errors.deadline='Submission deadline must be on or after the publish date.';
 if(data.submissionTime&&!/^([01]\d|2[0-3]):[0-5]\d$/.test(data.submissionTime))errors.submissionTime='Use HH:MM.';
 if(data.winProbability!==''&&data.winProbability!==undefined&&(Number(data.winProbability)>100||Number(data.winProbability)<0))errors.winProbability='Use 0–100%.';
 try{if(data.deadline)deadlineUtc(data);}catch{errors.timezone='Use a valid IANA time zone.';}
 if(['Go','No-Go'].includes(data.goDecision)&&!id)errors.goDecision='Create new tenders with Pending Review; use the approved decision workflow after registration.';if(data.goDecision==='No-Go'&&!data.noGoReason)errors.noGoReason='A No-Go decision needs a reason.';
 if(register&&req.settings.requireDocuments){if(!id)errors.documents='Save a draft, then upload the nine required documents before registration.';else{const docs=await c.query('SELECT DISTINCT type FROM documents WHERE tender_id=$1',[id]);const types=new Set(docs.rows.map(d=>d.type));if(spec.documents.some(d=>d.required&&!types.has(d.key)))errors.documents='Upload all nine mandatory documents before registration.';}}
 if(Object.keys(errors).length){const err=fail(422,'Please complete the highlighted fields.');err.fields=errors;throw err;}}
app.post('/api/tenders',async(req,res)=>{guard(req,'overview');const data={...tenderInput(req.body.data),timezone:req.body.data?.timezone||req.settings.timezone,requiredDocumentKeys:spec.documents.filter(d=>d.required).map(d=>d.key)};const draft=req.body.draft!==false;if(!draft&&['Go','No-Go'].includes(data.goDecision))throw fail(422,'Register with Pending Review, then use the Go / No-Go approval workflow.');await validateTender(data,!draft,req);const id=randomUUID();await transaction(async c=>{await c.query('INSERT INTO tenders(id,tender_id,data,draft,creator) VALUES($1,$2,$3,$4,$5)',[id,data.tenderId,JSON.stringify(data),draft,req.user.id]);await audit(c,req.user,id,draft?'Draft created':'Registered','overview',{},data);});res.status(201).json({id});});
app.put('/api/tenders/:id',async(req,res)=>{guard(req,'overview');await transaction(async c=>{const old=await getTender(req,req.params.id,c,true);if(req.body.revision!==old.revision)throw fail(409,'This tender changed since you opened it. Reload before saving.');const data={...old.data,...tenderInput(req.body.data)};for(const key of spec.fields.filter(f=>f.computed).map(f=>f.key))delete data[key];if(data.tenderId!==old.tender_id)throw fail(422,'Tender IDs cannot change after creation.');if(data.goDecision!==old.data.goDecision&&(['Go','No-Go'].includes(data.goDecision)||['Go','No-Go'].includes(old.data.goDecision)))throw fail(422,'Use the Go / No-Go tab to request an approved decision.');const rr=await recordsFor(old.id,c);if(classify(old,rr.calcRecords,req.settings).status==='Applied'&&['estimatedValue','emdAmount','currency','deadline','submissionTime'].some(k=>JSON.stringify(data[k])!==JSON.stringify(old.data[k]))&&!(new Date(old.data.unlockUntil)>new Date()))throw fail(423,'Commercial and submission fields are locked. Request a BU Head unlock.');const draft=req.body.draft===undefined?old.draft:req.body.draft;if(typeof draft!=='boolean')throw fail(422,'Draft status must be true or false.');await validateTender(data,!draft,req,c,old.id);await c.query('UPDATE tenders SET data=$1,draft=$2,revision=revision+1,updated_at=now() WHERE id=$3',[JSON.stringify(data),draft,old.id]);await audit(c,req.user,old.id,old.draft&&!draft?'Registered':'Updated','overview',old.data,data);});res.json({ok:true});});
function validateRecord(module,data,req){const def=MODULES[module];const errors={};for(const f of def.fields){const v=data[f.key];if(f.required&&(v===undefined||v===null||String(v).trim()===''))errors[f.key]='This field is required.';if(v!==undefined&&v!==''&&f.type==='number'&&(!Number.isFinite(Number(v))||Number(v)<0))errors[f.key]='Enter a non-negative number.';if(f.list&&v&&!req.masterValues.some(m=>m.list===f.list&&m.code===v))errors[f.key]='Choose a master value.';if(f.type==='date'&&v&&(!/^\d{4}-\d{2}-\d{2}$/.test(v)||Number.isNaN(new Date(v).getTime())))errors[f.key]='Enter a valid date.';}
 if(module==='scorecard')for(const key of Object.keys(req.settings.scoreWeights))if(Number(data[key])>5)errors[key]='Use a score from 0 to 5.';
 if(module==='submission'&&data.actualSubmission&&new Date(data.actualSubmission)>new Date(Date.now()+60000))errors.actualSubmission='Actual submission cannot be in the future.';if(module==='submission'&&data.status==='Submitted'&&(!data.actualSubmission||!data.receipt))errors.receipt='Submission requires date/time and an acknowledgement reference.';
 if(module==='instruments'&&data.issueDate&&data.expiryDate<data.issueDate)errors.expiryDate='Expiry must follow the issue date.';
 if(module==='award'&&data.outcome==='Awarded to Us'&&(!data.loaNumber||!data.awardedValue))errors.loaNumber='An award requires LOA/work order and awarded value.';
 if(module==='award'&&data.outcome==='Not Awarded to Us'&&(!data.winningBidder||!data.lossReason))errors.winningBidder='Record the winning bidder and loss reason.';
 if(Object.keys(errors).length){const e=fail(422,'Please complete the highlighted fields.');e.fields=errors;throw e;}}
app.post('/api/tenders/:id/records/:module',async(req,res)=>{const module=req.params.module;if(!MODULES[module])throw fail(404,'Unknown module.');guard(req,module);req.masterValues=(await pool.query('SELECT list,value,code FROM masters')).rows;await transaction(async c=>{const t=await getTender(req,req.params.id,c,true);if(t.draft)throw fail(422,'Register the tender before working on its later stages.');const rr=await recordsFor(t.id,c);const old=req.body.id?rr.records.find(r=>r.id===req.body.id&&r.module===module):MODULES[module].single?rr.records.find(r=>r.module===module):null;if(req.body.id&&!old)throw fail(404,'Record not found.');if(old?.data.approvalStatus==='Pending')throw fail(423,'This record has a pending approval. Wait for a decision before editing.');const recordInput=Object.fromEntries(Object.entries(req.body.data||{}).filter(([k])=>MODULES[module].fields.some(f=>f.key===k)));const data={...old?.data,...recordInput};delete data.approvalStatus;if(module==='submission'&&data.actualSubmission){if(!/[zZ]|[+-]\d{2}:\d{2}$/.test(data.actualSubmission)){const [date,time]=data.actualSubmission.split('T');data.actualSubmission=deadlineUtc({deadline:date,submissionTime:time.slice(0,5),timezone:t.data.timezone}).toISOString();}if(!Number.isFinite(new Date(data.actualSubmission).getTime()))throw fail(422,'Enter a valid actual submission date/time.');}if(!canSeePricing(req.user)||(!req.user.tenderPermissions&&req.headers['x-mobile']==='true'))for(const key of pricingFields){if(req.body.data?.[key]!==undefined&&req.body.data[key]!==old?.data[key])throw fail(403,'Pricing is restricted for this role or mobile view.');if(old?.data[key]!==undefined)data[key]=old.data[key];}
 validateRecord(module,data,req);
 if(module==='submission'){
 const wasSubmitted=classify(t,rr.calcRecords,req.settings).status==='Applied';if(wasSubmitted&&data.status!=='Withdrawn'&&!(new Date(t.data.unlockUntil)>new Date()))throw fail(423,'Submitted bid fields are locked. Request an approved unlock.');if(old?.data.submittedAt)data.submittedAt=old.data.submittedAt;
 if(wasSubmitted&&data.status==='Withdrawn'&&!(new Date(t.data.unlockUntil)>new Date())&&MODULES.submission.fields.some(f=>!['status','notes'].includes(f.key)&&JSON.stringify(data[f.key])!==JSON.stringify(old?.data[f.key])))throw fail(423,'Withdrawal can change status and notes only. Other submitted fields require an unlock.');if(data.status==='Submitted'&&!wasSubmitted){if(pricingFields.some(k=>JSON.stringify(data[k])!==JSON.stringify(old?.data[k])))throw fail(422,'Approved pricing changed. Save preparation and request a fresh approval before submitting.');if(t.data.goDecision!=='Go')throw fail(422,'An approved Go decision is required before bid submission.');if(old?.data.approvalStatus!=='Approved')throw fail(422,'Obtain pricing / submission approval first.');if(!rr.records.some(r=>r.module==='checklist'&&r.data.mandatory==='Yes'))throw fail(422,'Add and approve at least one mandatory submission checklist item.');if(rr.records.filter(r=>r.module==='checklist'&&r.data.mandatory==='Yes').some(r=>r.data.status!=='Completed'||r.data.approvalStatus!=='Approved'))throw fail(422,'Complete and approve all mandatory checklist items first.');if(Number(t.data.emdAmount)>0&&!rr.records.some(r=>r.module==='instruments'&&['Active','Extended'].includes(r.data.status)&&new Date(r.data.expiryDate+'T23:59:59Z')>=deadlineUtc(t.data)))throw fail(422,'A valid EMD / BG instrument covering the deadline is required.');data.submittedAt=data.actualSubmission;data.approvalStatus='Approved';}
 if(data.status==='Withdrawn'&&wasSubmitted){data.submittedAt=old?.data.submittedAt||old?.data.actualSubmission;data.actualSubmission=old?.data.actualSubmission;data.approvalStatus=old?.data.approvalStatus;}
 }
 if(module==='award'&&classify(t,rr.calcRecords,req.settings).status!=='Applied')throw fail(422,'Record an award only after a bid has been submitted.');
 if(module==='scorecard')Object.assign(data,scorecard(data,req.settings));
 let td={...t.data};
 if(module==='corrigenda'&&data.newDeadline){if(data.newDeadline<td.publishDate)throw fail(422,'Revised deadline cannot precede publication.');data.oldDeadline=old?.data.oldDeadline||td.deadline;data.oldTime=old?.data.oldTime||td.submissionTime;td.deadline=data.newDeadline;td.submissionTime=data.newTime||td.submissionTime;td.deadlineChangedAt=new Date().toISOString();await audit(c,req.user,t.id,'Deadline revised','overview',t.data,td);}
 const id=old?.id||randomUUID();await c.query('INSERT INTO records(id,tender_id,module,data,created_by) VALUES($1,$2,$3,$4,$5) ON CONFLICT(id) DO UPDATE SET data=EXCLUDED.data,updated_at=now()',[id,t.id,module,JSON.stringify(data),req.user.id]);await c.query('UPDATE tenders SET data=$1,revision=revision+1,updated_at=now() WHERE id=$2',[JSON.stringify(td),t.id]);await audit(c,req.user,t.id,old?'Updated':'Created',module,old?.data||{},data);});res.json({ok:true});});
app.delete('/api/tenders/:id/records/:record',async(req,res)=>{await transaction(async c=>{const t=await getTender(req,req.params.id,c,true);const r=(await c.query('SELECT * FROM records WHERE id=$1 AND tender_id=$2',[req.params.record,t.id])).rows[0];if(!r)throw fail(404,'Record not found.');guard(req,r.module,req.user.tenderPermissions?'delete':'write');if(MODULES[r.module]?.single||r.data.approvalStatus||r.module==='corrigenda')throw fail(422,'This workflow record must be corrected through its form and approval history.');await c.query('DELETE FROM records WHERE id=$1',[r.id]);await c.query('UPDATE tenders SET revision=revision+1,updated_at=now() WHERE id=$1',[t.id]);await audit(c,req.user,t.id,'Deleted',r.module,r.data,{});});res.json({ok:true});});
app.post('/api/tenders/:id/documents',upload.single('file'),async(req,res)=>{guard(req,'documents');if(!req.file)throw fail(400,'Choose a file.');const ext=path.extname(req.file.originalname).toLowerCase();if(!['.pdf','.doc','.docx','.xls','.xlsx','.ppt','.pptx','.jpg','.jpeg','.png','.zip'].includes(ext))throw fail(422,'Unsupported file type.');const type=req.body.type;if(!spec.documents.some(d=>d.key===type)&&!['OTHER','RECEIPT','LOA','CORRIGENDUM'].includes(type))throw fail(422,'Choose a valid document type.');const id=randomUUID();const file=path.join(fileRoot,id+ext);await fs.writeFile(file,req.file.buffer);try{await transaction(async c=>{const t=await getTender(req,req.params.id,c,true);const version=Number((await c.query('SELECT COALESCE(max(version),0)+1 AS v FROM documents WHERE tender_id=$1 AND type=$2',[t.id,type])).rows[0].v);await c.query('INSERT INTO documents(id,tender_id,type,version,filename,stored_path,mime,size,uploaded_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',[id,t.id,type,version,path.basename(req.file.originalname),file,req.file.mimetype,req.file.size,req.user.id]);await c.query('UPDATE tenders SET revision=revision+1,updated_at=now() WHERE id=$1',[t.id]);await audit(c,req.user,t.id,'Document uploaded','documents',{}, {type,version,filename:req.file.originalname});});}catch(e){await fs.unlink(file);throw e;}res.json({id});});
app.get('/api/documents/:id',async(req,res)=>{const d=(await pool.query('SELECT * FROM documents WHERE id=$1',[req.params.id])).rows[0];if(!d)throw fail(404,'Document not found.');await getTender(req,d.tender_id);res.download(d.stored_path,d.filename);});
app.post('/api/tenders/:id/approvals',async(req,res)=>{const {module,recordId,comment}=req.body;if(!['scorecard','submission','award','unlock','checklist','registration'].includes(module))throw fail(422,'This module does not support approval.');guard(req,module==='unlock'?'submission':module==='registration'?'overview':module);await transaction(async c=>{const t=await getTender(req,req.params.id,c,true);const rr=await recordsFor(t.id,c);const r=rr.records.find(x=>x.id===recordId&&x.module===module);if(module!=='unlock'&&module!=='registration'&&!r)throw fail(422,'Save the record before requesting approval.');if(r?.data.approvalStatus==='Approved')throw fail(422,'This record is already approved.');if(r?.module==='submission'&&classify(t,rr.calcRecords,req.settings).status==='Applied')throw fail(422,'The bid has already been submitted.');if(module==='unlock'&&classify(t,rr.calcRecords,req.settings).status!=='Applied')throw fail(422,'Only submitted bids need an unlock.');const id=randomUUID();await c.query('INSERT INTO approvals(id,tender_id,module,record_id,requested_by,comment,requested_revision,payload) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[id,t.id,module,r?.id||null,req.user.id,comment||'',t.revision,JSON.stringify(r?.data||{})]);if(r)await c.query("UPDATE records SET data=jsonb_set(data,'{approvalStatus}','\"Pending\"') WHERE id=$1",[r.id]);await audit(c,req.user,t.id,'Approval requested',module,{}, {approvalId:id,comment});});await runReminders();res.json({ok:true});});
app.get('/api/approvals',async(req,res)=>{const rows=(await pool.query('SELECT a.*,t.tender_id AS tender_ref,t.data->>\'title\' AS tender_title,u.name AS requested_by_name FROM approvals a JOIN tenders t ON t.id=a.tender_id LEFT JOIN users u ON u.id=a.requested_by ORDER BY created_at DESC')).rows;const visible=[];for(const row of rows)try{await getTender(req,row.tender_id);visible.push({...row,payload:sanitizeRecord(req,{data:row.payload}).data,canApprove:permitted(req.user,row.module,'approve',req.settings)});}catch{}res.json(visible);});
app.post('/api/approvals/:id/decision',async(req,res)=>{if(!['Approved','Rejected'].includes(req.body.decision))throw fail(422,'Choose Approved or Rejected.');await transaction(async c=>{const a=(await c.query('SELECT * FROM approvals WHERE id=$1 FOR UPDATE',[req.params.id])).rows[0];if(!a)throw fail(404,'Approval not found.');guard(req,a.module,'approve');if(a.status!=='Pending')throw fail(409,'This approval has already been decided.');const t=await getTender(req,a.tender_id,c,true);if(a.record_id){const r=(await c.query('SELECT * FROM records WHERE id=$1',[a.record_id])).rows[0];if(!r||JSON.stringify(Object.fromEntries(Object.entries(r.data).filter(([k])=>k!=='approvalStatus')))!==JSON.stringify(a.payload))throw fail(409,'The record changed after this approval was requested.');const data={...r.data,approvalStatus:req.body.decision};if(a.module==='submission'&&req.body.decision==='Approved')data.status='Approved for Submission';await c.query('UPDATE records SET data=$1,updated_at=now() WHERE id=$2',[JSON.stringify(data),r.id]);if(a.module==='scorecard'&&req.body.decision==='Approved'){const td={...t.data,goDecision:data.proposedDecision,decisionDate:new Date().toISOString().slice(0,10),approvedBy:req.user.name,winProbability:data.winProbability??t.data.winProbability,pipelineStatus:data.proposedDecision==='Go'?'Go - Moved to Bid Preparation':data.proposedDecision==='No-Go'?'No-Go - Dropped':data.proposedDecision==='Hold / Awaiting Info'?'On Hold':'Under Review',noGoReason:data.proposedDecision==='No-Go'?data.reason:'',score:data.score,recommendation:data.recommendation};await c.query('UPDATE tenders SET data=$1 WHERE id=$2',[JSON.stringify(td),t.id]);await audit(c,req.user,t.id,'Decision applied','overview',t.data,td);}}
 if(a.module==='unlock'&&req.body.decision==='Approved'){const td={...t.data,unlockUntil:new Date(Date.now()+3600000).toISOString()};await c.query('UPDATE tenders SET data=$1 WHERE id=$2',[JSON.stringify(td),t.id]);await audit(c,req.user,t.id,'Unlocked for one hour','overview',t.data,td);}
 await c.query('UPDATE approvals SET status=$1,comment=$2,decided_by=$3,decided_at=now() WHERE id=$4',[req.body.decision,req.body.comment||a.comment,req.user.id,a.id]);await c.query('UPDATE tenders SET revision=revision+1,updated_at=now() WHERE id=$1',[t.id]);await audit(c,req.user,t.id,'Approval '+req.body.decision,a.module,{}, {approvalId:a.id,comment:req.body.comment});});res.json({ok:true});});
app.get('/api/audit',async(req,res)=>{if(!isAdmin(req)&&!req.params.id&&!req.query.tenderId)throw fail(403,'Global audit is available to administrators.');if(req.query.tenderId)await getTender(req,req.query.tenderId);const rows=(await pool.query('SELECT a.*,u.name AS actor_name,t.tender_id AS tender_ref FROM audit a LEFT JOIN users u ON u.id=a.actor LEFT JOIN tenders t ON t.id=a.tender_id WHERE ($1::uuid IS NULL OR a.tender_id=$1) ORDER BY a.created_at DESC LIMIT 1000',[req.query.tenderId||null])).rows;res.json(rows.map(x=>sanitizeAudit(req,x)));});
app.get('/api/notifications',async(req,res)=>res.json((await pool.query('SELECT n.*,t.tender_id AS tender_ref FROM notifications n LEFT JOIN tenders t ON t.id=n.tender_id WHERE n.user_id=$1 ORDER BY n.created_at DESC LIMIT 200',[req.user.id])).rows));
app.post('/api/notifications/:id/read',async(req,res)=>{await pool.query('UPDATE notifications SET read_at=now() WHERE id=$1 AND user_id=$2',[req.params.id,req.user.id]);res.json({ok:true});});
app.get('/api/portal',async(req,res)=>{const rows=(await pool.query('SELECT * FROM portal_feed ORDER BY created_at DESC')).rows;const tenders=await listTenders(req);res.json(rows.map(p=>{const match=tenders.find(t=>t.data.clientRef?.toLowerCase()===p.data.clientRef?.toLowerCase()&&t.data.client?.toLowerCase()===p.data.client?.toLowerCase());return {...p,registered:!!match&&!match.draft,matchedTenderId:match?.id,matchedDraft:!!match?.draft};}));});
app.post('/api/portal',async(req,res)=>{guard(req,'overview');if(!req.body.title||!req.body.client||!req.body.clientRef)throw fail(422,'Title, client and client reference are required.');await pool.query('INSERT INTO portal_feed(id,data,created_by) VALUES($1,$2,$3)',[randomUUID(),JSON.stringify(req.body),req.user.id]);await audit(pool,req.user,null,'Portal tender added','portal',{},req.body);res.json({ok:true});});
app.delete('/api/portal/:id',async(req,res)=>{if(!isAdmin(req))throw fail(403,'Administrator access required.');await pool.query('DELETE FROM portal_feed WHERE id=$1',[req.params.id]);res.json({ok:true});});
app.get('/api/admin/users',async(req,res)=>{if(!isAdmin(req))throw fail(403,'Administrator access required.');res.json((await pool.query('SELECT * FROM users ORDER BY name')).rows.map(cleanUser));});
app.post('/api/admin/users',async(req,res)=>{if(bdmsEnabled())throw fail(403,'Manage users and Tender privileges in the BDMS user master.');if(!isAdmin(req))throw fail(403,'Administrator access required.');const d=req.body;if(!d.name||!d.email||!Array.isArray(d.roles)||!d.roles.length||d.roles.some(r=>!ROLES.includes(r)))throw fail(422,'Name, email and valid roles are required.');if(!d.id&&String(d.password||'').length<10)throw fail(422,'Initial password must have at least 10 characters.');await transaction(async c=>{if(d.id){const old=(await c.query('SELECT * FROM users WHERE id=$1 FOR UPDATE',[d.id])).rows[0];if(!old)throw fail(404,'User not found.');if(d.id===req.user.id&&(!d.roles.includes('System Administrator')||d.active===false))throw fail(422,'You cannot disable your own administrator access.');await c.query('UPDATE users SET name=$1,email=$2,roles=$3,business_unit=$4,active=$5,phone=$7 WHERE id=$6',[d.name,d.email,JSON.stringify(d.roles),d.businessUnit||null,d.active!==false,d.id,d.phone||null]);if(d.password){if(d.password.length<10)throw fail(422,'Password must have at least 10 characters.');await c.query('UPDATE users SET password_hash=$1 WHERE id=$2',[hashPassword(d.password),d.id]);await c.query('DELETE FROM sessions WHERE user_id=$1',[d.id]);}await audit(c,req.user,null,'User updated','users',cleanUser(old),{...d,password:undefined});}else{await c.query('INSERT INTO users(id,name,email,password_hash,roles,business_unit,phone) VALUES($1,$2,$3,$4,$5,$6,$7)',[randomUUID(),d.name,d.email,hashPassword(d.password),JSON.stringify(d.roles),d.businessUnit||null,d.phone||null]);await audit(c,req.user,null,'User created','users',{}, {...d,password:undefined});}});res.json({ok:true});});
app.post('/api/admin/masters',async(req,res)=>{if(!isAdmin(req))throw fail(403,'Administrator access required.');const d=req.body;if(!spec.masters[d.list]||!String(d.value||'').trim())throw fail(422,'Choose a list and enter a value.');await transaction(async c=>{if(d.id){const old=(await c.query('SELECT * FROM masters WHERE id=$1',[d.id])).rows[0];if(!old||old.list!==d.list)throw fail(404,'Master not found.');await c.query('UPDATE masters SET value=$1,active=$2 WHERE id=$3',[d.value.trim(),d.active!==false,d.id]);await audit(c,req.user,null,'Master updated','masters',old,d);}else{await c.query('INSERT INTO masters(id,list,value,code) VALUES($1,$2,$3,$3)',[randomUUID(),d.list,d.value.trim()]);await audit(c,req.user,null,'Master created','masters',{},d);}});res.json({ok:true});});
app.put('/api/admin/settings',async(req,res)=>{if(!isAdmin(req))throw fail(403,'Administrator access required.');const d={...req.settings,...req.body};if(!(Number(d.urgentDays)>Number(d.criticalDays)&&Number(d.criticalDays)>Number(d.dangerHours)/24&&Number(d.dangerHours)>Number(d.finalHours)&&Number(d.finalHours)>0))throw fail(422,'Alert bands must decrease from urgent days to final hours.');d.reminderOffsets=[d.urgentDays*1440,d.criticalDays*1440,d.dangerHours*60,d.finalHours*60];if(!Object.values(d.scoreWeights).every(x=>Number.isFinite(Number(x))&&Number(x)>=0)||Object.values(d.scoreWeights).reduce((a,b)=>a+Number(b),0)<=0)throw fail(422,'Score weights must be non-negative with a positive total.');if(!(Number(d.scoreGo)>Number(d.scoreHold)&&Number(d.scoreGo)<=100&&Number(d.scoreHold)>=0))throw fail(422,'Use score bands with Go > Hold, within 0–100.');if(!Array.isArray(d.requiredRegistrationFields)||d.requiredRegistrationFields.some(k=>!spec.fields.some(f=>f.key===k)))throw fail(422,'Unknown required registration field.');await pool.query('UPDATE settings SET data=$1 WHERE id=1',[JSON.stringify(d)]);await audit(pool,req.user,null,'Settings updated','settings',req.settings,d);res.json({ok:true});});
app.get('/api/admin/deliveries',async(req,res)=>{if(!isAdmin(req))throw fail(403,'Administrator access required.');res.json((await pool.query('SELECT d.*,n.title,n.message FROM deliveries d JOIN notifications n ON n.id=d.notification_id ORDER BY d.created_at DESC LIMIT 300')).rows);});
const importFields=spec.fields.filter(f=>!f.computed);
app.post('/api/import/form',upload.single('file'),async(req,res)=>{
 guard(req,'overview');
 if(!req.file)throw fail(400,'Choose an Excel or CSV file.');
 const masters=(await pool.query('SELECT list,code,value,active FROM masters')).rows;
 const users=(await pool.query('SELECT name,active FROM users')).rows;
 res.json(await readFormImport(req.file.buffer,req.file.originalname,spec.fields,masters,users));
});
installPortalImport(app,upload,pool,guard,audit);
app.get('/api/import/template',async(req,res)=>{guard(req,'overview');const w=new ExcelJS.Workbook();const sheet=w.addWorksheet('Tenders');sheet.addRow(importFields.map(f=>f.key));sheet.getRow(1).font={bold:true,color:{argb:'FFFFFFFF'}};sheet.getRow(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF142E37'}};sheet.views=[{state:'frozen',ySplit:1}];sheet.columns.forEach((col,i)=>col.width=Math.max(18,importFields[i].key.length+3));const dictionary=w.addWorksheet('Field guide');dictionary.addRow(['Column','Label','Required for registration','Master list']);for(const f of importFields)dictionary.addRow([f.key,f.label,req.settings.requiredRegistrationFields.includes(f.key)?'Yes':'No',f.list||'']);const dropdowns=w.addWorksheet('Master values');dropdowns.addRow(['List','Value']);for(const m of (await pool.query('SELECT * FROM masters WHERE active ORDER BY list,value')).rows)dropdowns.addRow([m.list,m.code]);res.setHeader('Content-Disposition','attachment; filename="tender-import-template.xlsx"');res.type('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');await w.xlsx.write(res);res.end();});
app.post('/api/import',upload.single('file'),async(req,res)=>{guard(req,'overview');if(!req.file)throw fail(400,'Choose an Excel or CSV file.');const w=new ExcelJS.Workbook();const ext=path.extname(req.file.originalname).toLowerCase();if(ext==='.xlsx')await w.xlsx.load(req.file.buffer);else if(ext==='.csv'){const {Readable}=await import('node:stream');await w.csv.read(Readable.from(req.file.buffer));}else throw fail(422,'Use .xlsx or .csv.');const sheet=w.getWorksheet('Tenders')||w.worksheets[0];if(!sheet)throw fail(422,'The workbook has no tender sheet.');if(sheet.rowCount>1001)throw fail(422,'Upload up to 1,000 tenders at a time.');const headers=sheet.getRow(1).values.slice(1).map(x=>String(x||''));if(!headers.includes('tenderId'))throw fail(422,'First row must contain the template column headers.');const results=[];const seenIds=new Set(),seenRefs=new Set();const preview=req.body.preview!=='false';for(let row=2;row<=sheet.rowCount;row++){const vals=sheet.getRow(row).values.slice(1);if(!vals.some(v=>v!==null&&v!==undefined&&v!==''))continue;const data={timezone:req.settings.timezone,goDecision:'Pending Review',priority:'Medium',pipelineStatus:'Identified',owner:req.user.name,businessUnit:req.user.businessUnit||'',requiredDocumentKeys:spec.documents.filter(d=>d.required).map(d=>d.key)};try{headers.forEach((key,i)=>{const field=importFields.find(f=>f.key===key);if(field){const val=importCell(vals[i],field);if(val!=='')data[key]=val;}});const ref=[data.client,data.clientRef].map(v=>String(v||'').toLowerCase()).join('|');if(seenIds.has(data.tenderId)||(data.clientRef&&seenRefs.has(ref)))throw fail(422,'Duplicate tender ID or client reference in this file.');seenIds.add(data.tenderId);if(data.clientRef)seenRefs.add(ref);await validateTender(data,false,req);const dup=await pool.query('SELECT 1 FROM tenders WHERE tender_id=$1 OR (lower(data->>\'client\')=lower($2) AND lower(data->>\'clientRef\')=lower($3) AND $3<>\'\')',[data.tenderId,data.client||'',data.clientRef||'']);if(dup.rowCount)throw fail(422,'Tender ID or client reference already exists.');if(!preview)await transaction(async c=>{const id=randomUUID();await c.query('INSERT INTO tenders(id,tender_id,data,draft,creator) VALUES($1,$2,$3,true,$4)',[id,data.tenderId,JSON.stringify(data),req.user.id]);await audit(c,req.user,id,'Imported as draft','overview',{},data);});results.push({row,tenderId:data.tenderId,status:preview?'Valid':'Imported as draft'});}catch(e){results.push({row,tenderId:data.tenderId,status:'Rejected',error:e.message,fields:e.fields});}}
 res.json({preview,results,valid:results.filter(r=>r.status!=='Rejected').length,rejected:results.filter(r=>r.status==='Rejected').length});});
app.get('/api/export',async(req,res)=>{const all=(await listTenders(req)).filter(t=>!t.draft);let rows=all;if(req.query.scope==='pending')rows=rows.filter(t=>t.calculated.status==='Pending');if(req.query.scope==='applied'||req.query.scope==='results')rows=rows.filter(t=>t.calculated.status==='Applied');if(req.query.scope==='not-applied')rows=rows.filter(t=>t.calculated.status==='Not Applied');if(req.query.search)rows=rows.filter(t=>[t.tender_id,t.data.title,t.data.client].join(' ').toLowerCase().includes(req.query.search.toLowerCase()));for(const [query,key]of [['sector','sector'],['owner','owner'],['priority','priority'],['businessUnit','businessUnit'],['currency','currency']])if(req.query[query])rows=rows.filter(t=>t.data[key]===req.query[query]);const w=new ExcelJS.Workbook();const sheet=w.addWorksheet('Tender report');sheet.addRow(['Tender ID','Title','Client','Sector','Business unit','Owner','Priority','Currency','Estimated value','Deadline','Status','Reason','Award category','Awarded value','LOA / Work order','Winning bidder','Loss reason']);rows.forEach(t=>sheet.addRow([t.tender_id,t.data.title,t.data.client,t.data.sector,t.data.businessUnit,t.data.owner,t.data.priority,t.data.currency,Number(t.data.estimatedValue||0),t.data.deadline,t.calculated.status,t.calculated.notAppliedReason,t.calculated.awardCategory,t.award.approvalStatus==='Approved'?Number(t.award.awardedValue||0):null,t.award.loaNumber,t.award.winningBidder,t.award.lossReason]));sheet.getRow(1).font={bold:true,color:{argb:'FFFFFFFF'}};sheet.getRow(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF142E37'}};sheet.columns.forEach((c,i)=>c.width=i===1?50:22);sheet.views=[{state:'frozen',ySplit:1}];sheet.autoFilter={from:'A1',to:'Q1'};res.setHeader('Content-Disposition','attachment; filename="tender-report.xlsx"');await w.xlsx.write(res);res.end();});
app.get('/api/admin/backup',async(req,res)=>{if(!isAdmin(req))throw fail(403,'Administrator access required.');const backup={version:1,createdAt:new Date().toISOString(),tables:{}};await transaction(async c=>{await c.query('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');for(const table of ['users','masters','settings','tenders','records','documents','approvals','audit','notifications','deliveries','portal_feed']){const rows=(await c.query(`SELECT * FROM ${table}`)).rows;backup.tables[table]=rows;if(table==='documents')for(const d of rows)d.content=(await fs.readFile(d.stored_path)).toString('base64');}});res.attachment('tender-backup-'+new Date().toISOString().slice(0,10)+'.json');res.json(backup);});
app.post('/api/admin/restore',restoreUpload.single('file'),async(req,res)=>{if(bdmsEnabled())throw fail(403,'Contact your administrator for a data restore; BDMS identities must be preserved.');if(!isAdmin(req))throw fail(403,'Administrator access required.');if(!req.file)throw fail(422,'Choose a backup.');const b=JSON.parse(req.file.buffer.toString('utf8'));if(b.version!==1||!b.tables?.tenders)throw fail(422,'Invalid backup format.');const count=Number((await pool.query('SELECT count(*) FROM tenders')).rows[0].count);if(count)throw fail(409,'Restore requires an empty tender database to avoid overwriting your records.');const allowed=['users','masters','settings','tenders','records','documents','approvals','audit','notifications','deliveries','portal_feed'];const writes=[];try{await transaction(async c=>{const userMap=new Map();for(const user of b.tables.users||[]){const existing=(await c.query('SELECT id FROM users WHERE lower(email)=lower($1)',[user.email])).rows[0];userMap.set(user.id,existing?.id||user.id);}for(const table of allowed){for(const item of b.tables[table]||[]){const row={...item};if(table==='users'&&userMap.get(row.id)!==row.id)continue;for(const key of ['creator','actor','user_id','created_by','uploaded_by','requested_by','decided_by'])if(row[key]&&userMap.has(row[key]))row[key]=userMap.get(row[key]);if(table==='audit')delete row.id;if(table==='documents'){const ext=path.extname(row.filename).toLowerCase();if(!['.pdf','.doc','.docx','.xls','.xlsx','.ppt','.pptx','.jpg','.jpeg','.png','.zip'].includes(ext))throw fail(422,'Invalid document filename.');const target=path.join(fileRoot,randomUUID()+ext);await fs.writeFile(target,Buffer.from(row.content,'base64'));writes.push(target);row.stored_path=target;delete row.content;}const cols=Object.keys(row);const actual=(await c.query('SELECT column_name FROM information_schema.columns WHERE table_schema=\'public\' AND table_name=$1',[table])).rows.map(x=>x.column_name);if(cols.some(k=>!actual.includes(k)))throw fail(422,'Invalid backup columns.');const vals=cols.map(k=>row[k]&&typeof row[k]==='object'?JSON.stringify(row[k]):row[k]);let conflict='ON CONFLICT DO NOTHING';if(table==='settings')conflict='ON CONFLICT(id) DO UPDATE SET data=EXCLUDED.data';if(table==='masters')conflict='ON CONFLICT(list,code) DO UPDATE SET value=EXCLUDED.value,active=EXCLUDED.active';await c.query(`INSERT INTO ${table} (${cols.map(k=>'"'+k+'"').join(',')}) VALUES(${cols.map((_,i)=>'$'+(i+1)).join(',')}) ${conflict}`,vals);}}await c.query("SELECT setval('audit_id_seq',GREATEST(1,(SELECT COALESCE(max(id),1) FROM audit)))");await audit(c,req.user,null,'Backup restored','backup',{}, {createdAt:b.createdAt});});}catch(e){for(const file of writes)await fs.unlink(file).catch(()=>{});throw e;}res.json({ok:true});});
async function notify(tenderId,user,event,title,message,channels=[]){const id=randomUUID();const r=await pool.query('INSERT INTO notifications(id,tender_id,user_id,event_key,title,message) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT DO NOTHING RETURNING id',[id,tenderId,user.id,event+':'+user.id,title,message]);if(!r.rowCount)return;for(const channel of channels)await pool.query('INSERT INTO deliveries(id,notification_id,channel,status) VALUES($1,$2,$3,$4)',[randomUUID(),id,channel,channel==='email'&&!process.env.SMTP_HOST||channel==='whatsapp'&&(!process.env.WHATSAPP_TOKEN||!process.env.WHATSAPP_PHONE_ID||!process.env.WHATSAPP_TEMPLATE||!user.phone)?'Not configured':'Queued']);}
let reminderRunning=false;
async function runReminders(){if(reminderRunning)return;reminderRunning=true;try{if(bdmsEnabled())await syncDirectory(pool);const config=await settings();const users=(await pool.query('SELECT * FROM users WHERE active=true')).rows;const tenders=(await pool.query('SELECT * FROM tenders WHERE draft=false')).rows;const allRecords=(await pool.query('SELECT * FROM records')).rows;const now=new Date();for(const t of tenders){const records=allRecords.filter(r=>r.tender_id===t.id);const calc=classify(t,records,config,now);const eligible=users.filter(u=>!u.business_unit||u.business_unit===t.data.businessUnit);if(calc.status==='Pending'&&calc.deadlineUtc){const minutes=(new Date(calc.deadlineUtc)-now)/60000;for(const offset of config.reminderOffsets){if(minutes<=offset&&minutes>0){const hours=offset/60;const roles=config.notificationRecipients[String(offset)]||['Bid Manager','BU Head'];for(const u of eligible.filter(u=>u.name===t.data.owner||u.roles.some(r=>roles.includes(r))))await notify(t.id,u,`deadline:${t.id}:${calc.deadlineUtc}:${offset}`,`${t.tender_id} · Deadline approaching`,`${t.data.title}: submission closes within ${hours>=24?hours/24+' days':hours+' hours'}.`,['whatsapp']);}}}if(calc.notAppliedReason==='Deadline Missed')for(const u of eligible.filter(u=>u.name===t.data.owner||u.roles.includes('BU Head')))await notify(t.id,u,`missed:${t.id}:${calc.deadlineUtc}`,`${t.tender_id} · Deadline missed`,t.data.title,['whatsapp']);if(t.data.deadlineChangedAt&&Date.now()-new Date(t.data.deadlineChangedAt)<172800000)for(const u of eligible.filter(u=>u.name===t.data.owner||u.roles.includes('Bid Manager')))await notify(t.id,u,`extension:${t.id}:${t.data.deadlineChangedAt}`,`${t.tender_id} · Deadline revised`,`New closing date: ${t.data.deadline} ${t.data.submissionTime}.`);
 for(const inst of records.filter(r=>r.module==='instruments'&&['Active','Extended'].includes(r.data.status))){const days=(new Date(inst.data.expiryDate)-now)/86400000;if(days<=config.instrumentReminderDays)for(const u of eligible.filter(u=>u.roles.includes('Finance / Treasury')||u.name===t.data.owner))await notify(t.id,u,`instrument:${inst.id}:${inst.data.expiryDate}`,`${t.tender_id} · Instrument expiry`,`${inst.data.reference} expires ${inst.data.expiryDate}.`,['email']);}}
 const pending=(await pool.query("SELECT a.*,t.tender_id AS ref,t.data FROM approvals a JOIN tenders t ON t.id=a.tender_id WHERE a.status='Pending'")).rows;for(const a of pending)for(const u of users.filter(u=>permitted(cleanUser(u),a.module,'approve',config)&&(!u.business_unit||u.business_unit===a.data.businessUnit)))await notify(a.tender_id,u,`approval:${a.id}`,`${a.ref} · Approval requested`,`${MODULES[a.module]?.label||a.module} is ready for review.`,['email']);
 const decided=(await pool.query("SELECT a.*,t.tender_id AS ref FROM approvals a JOIN tenders t ON t.id=a.tender_id WHERE a.status<>'Pending'")).rows;for(const a of decided){const u=users.find(u=>u.id===a.requested_by);if(u)await notify(a.tender_id,u,`decision:${a.id}`,`${a.ref} · ${a.module} ${a.status.toLowerCase()}`,a.comment||'Your approval request has been reviewed.');}
 const feed=(await pool.query('SELECT * FROM portal_feed')).rows;for(const p of feed)if(!tenders.some(t=>t.data.clientRef?.toLowerCase()===p.data.clientRef?.toLowerCase()&&t.data.client?.toLowerCase()===p.data.client?.toLowerCase()))for(const u of users.filter(u=>u.roles.some(r=>['BD Executive','Bid Manager'].includes(r))))await notify(null,u,`portal:${p.id}`,'Portal tender not registered',p.data.title);
 const queued=(await pool.query("SELECT d.*,n.title,n.message,COALESCE(u.contact_email,u.email) AS email,u.phone FROM deliveries d JOIN notifications n ON n.id=d.notification_id JOIN users u ON u.id=n.user_id WHERE d.status='Queued' AND d.next_attempt<=now() AND u.active=true LIMIT 20")).rows;for(const d of queued){try{if(d.channel==='email'){const transport=nodemailer.createTransport({host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT||587),secure:process.env.SMTP_SECURE==='true',auth:process.env.SMTP_USER?{user:process.env.SMTP_USER,pass:process.env.SMTP_PASSWORD}:undefined});await transport.sendMail({from:process.env.SMTP_FROM,to:d.email,subject:d.title,text:d.message});}else {if(!d.phone)throw new Error('Recipient WhatsApp phone number is missing.');const response=await fetch(`https://graph.facebook.com/${process.env.WHATSAPP_GRAPH_VERSION||'v23.0'}/${process.env.WHATSAPP_PHONE_ID}/messages`,{method:'POST',headers:{Authorization:'Bearer '+process.env.WHATSAPP_TOKEN,'Content-Type':'application/json'},body:JSON.stringify({messaging_product:'whatsapp',to:d.phone.replace(/[^0-9]/g,''),type:'template',template:{name:process.env.WHATSAPP_TEMPLATE,language:{code:process.env.WHATSAPP_LANGUAGE||'en'},components:[{type:'body',parameters:[{type:'text',text:d.title},{type:'text',text:d.message}]}]}}),signal:AbortSignal.timeout(15000)});if(!response.ok)throw new Error('WhatsApp delivery rejected: '+(await response.text()).slice(0,300));}await pool.query("UPDATE deliveries SET status='Sent',attempts=attempts+1 WHERE id=$1",[d.id]);}catch(e){await pool.query("UPDATE deliveries SET status=$1,error=$2,attempts=attempts+1,next_attempt=now()+interval '10 minutes' WHERE id=$3",[d.attempts>=2?'Failed':'Queued',e.message,d.id]);}}
 }catch(e){console.error('Reminder worker:',e.message);}finally{reminderRunning=false;}}
setInterval(runReminders,30000).unref();
app.post('/api/admin/run-reminders',async(req,res)=>{if(!isAdmin(req))throw fail(403,'Administrator access required.');await runReminders();res.json({ok:true});});
if(existsSync('dist/index.html')){app.use(express.static('dist',{maxAge:'1h'}));app.get('/{*path}',(req,res,next)=>req.path.startsWith('/api/')?next(fail(404,'API route not found.')):res.sendFile(path.resolve('dist/index.html')));}else{const {createServer}=await import('vite');const vite=await createServer({server:{middlewareMode:true},appType:'spa'});app.use(vite.middlewares);}
app.use((err,req,res,next)=>{console.error(err.status?err.message:err);if(res.headersSent)return next(err);let status=err.status||500,message=err.message;if(err.code==='23505'){status=409;message='This Tender ID, client reference, master value or pending approval already exists.';}if(err.code==='22P02'){status=400;message='Invalid record identifier.';}if(err instanceof multer.MulterError){status=422;message='File upload failed: '+err.message;}res.status(status).json({error:status===500?'The request could not be completed. Please try again.':message,fields:err.fields});});
const server=app.listen(PORT,runtime.host,()=>{console.log(`Tender Tracker ready: http://localhost:${PORT}`);console.log(`PostgreSQL data: ${process.env.TENDER_DATA_DIR||'Local AppData / TenderTracker / postgres'}`);runReminders();});
async function shutdown(){server.close();await pool.end();if(embedded)await embedded.stop();process.exit(0);}process.on('SIGINT',shutdown);process.on('SIGTERM',shutdown);
