export const ROLES=['BD Executive','Bid Manager','Document Controller','Estimation','Technical','Legal','Finance / Treasury','BU Head','Bid Committee / Director','System Administrator'];
const f=(key,label,type='text',list=null,required=false)=>({key,label,type,list,required});
export const MODULES={
  scorecard:{label:'Go / No-Go',icon:'Compass',single:true,roles:['Bid Manager'],approvers:['Bid Committee / Director'],fields:[f('strategicFit','Strategic fit (0–5)','number'),f('eligibilityScore','Eligibility (0–5)','number'),f('technicalCapability','Technical capability (0–5)','number'),f('financialCapacity','Financial capacity (0–5)','number'),f('competitiveness','Competitiveness (0–5)','number'),f('riskScore','Risk acceptability (0–5)','number'),f('proposedDecision','Proposed decision','select','GoDecision',true),f('reason','Decision rationale','textarea',null,true),f('decisionDate','Decision date','date'),f('winProbability','Win probability (%)','number')]},
  queries:{label:'Pre-Bid Queries',single:false,roles:['Bid Manager','Technical'],fields:[f('subject','Subject','text',null,true),f('clause','Clause / reference'),f('question','Question','textarea',null,true),f('impact','Impact area','select','QueryImpact'),f('owner','Responsible person','user'),f('dueDate','Response due date','date'),f('status','Query status','select','QueryStatus',true),f('response','Client response','textarea'),f('responseDate','Response date','date')]},
  corrigenda:{label:'Corrigendum',single:false,roles:['Document Controller','Bid Manager'],fields:[f('number','Corrigendum / addendum no.','text',null,true),f('issueDate','Issue date','date',null,true),f('kind','Document kind','select','DocKind'),f('changeType','Change type','select','CorrType',true),f('description','Change summary','textarea',null,true),f('newDeadline','Revised submission deadline','date'),f('newTime','Revised closing time','time'),f('impact','Impact and actions','textarea'),f('reviewStatus','Impact review','select','TaskStatus'),f('fileId','Supporting document ID')]},
  submission:{label:'Bid Preparation',single:true,roles:['Bid Manager','Estimation','Technical','Legal'],approvers:['BU Head'],fields:[f('kickoffDate','Bid kickoff date','date'),f('technicalStatus','Technical preparation','select','TaskStatus'),f('commercialStatus','Commercial preparation','select','TaskStatus'),f('legalStatus','Legal review','select','TaskStatus'),f('costEstimate','Cost estimate','number'),f('quotedPrice','Quoted bid price','number'),f('margin','Target margin (%)','number'),f('mode','Submission mode','select','SubMode'),f('status','Submission status','select','SubStatus',true),f('actualSubmission','Actual submission date & time','datetime-local'),f('receipt','Submission reference / acknowledgement'),f('receiptFileId','Receipt document ID'),f('notes','Preparation notes','textarea')]},
  instruments:{label:'EMD / BG',single:false,roles:['Finance / Treasury'],fields:[f('reference','Instrument reference','text',null,true),f('type','Instrument type','select','InstrType',true),f('form','Instrument form','select','InstrForm'),f('amount','Amount','number',null,true),f('bank','Issuing bank'),f('issueDate','Issue date','date'),f('expiryDate','Expiry date','date',null,true),f('claimDate','Claim deadline','date'),f('status','Instrument status','select','BGStatus'),f('refundStatus','Refund status','select','Refund'),f('refundDate','Refund date','date'),f('refundAmount','Refund amount','number'),f('notes','Extension / release notes','textarea')]},
  checklist:{label:'Submission Checklist',single:false,roles:['Bid Manager','Document Controller'],approvers:['Bid Manager'],fields:[f('item','Checklist item','text',null,true),f('owner','Responsible person','user'),f('mandatory','Mandatory','select','YesNo',true),f('dueDate','Due date','date'),f('status','Task status','select','TaskStatus',true),f('evidence','Evidence / notes','textarea')]},
  evaluation:{label:'Evaluation',single:true,roles:['Bid Manager'],fields:[f('stage','Evaluation stage','select','EvalStage',true),f('method','Evaluation method','select','EvalMethod'),f('responsive','Responsiveness','select','Responsive'),f('technicalOpening','Technical opening date','date'),f('financialOpening','Financial opening date','date'),f('technicalScore','Technical score','number'),f('financialScore','Financial score','number'),f('combinedScore','Combined score','number'),f('rank','Our rank','select','Rank'),f('negotiatedPrice','Negotiated price','number'),f('clientContact','Client contact'),f('nextAction','Next action','textarea'),f('nextActionDate','Next action date','date')]},
  award:{label:'Award & Post-Mortem',single:true,roles:['Bid Manager'],approvers:['BU Head'],fields:[f('outcome','Proposed outcome','select','Outcome',true),f('outcomeDate','Outcome date','date',null,true),f('awardedValue','Awarded contract value','number'),f('loaNumber','LOA / work order number'),f('loaDate','LOA date','date'),f('winningBidder','Winning bidder'),f('lossReason','Primary loss reason','select','LossReason'),f('controllability','Loss controllability','select','Controllable'),f('contractStart','Contract start date','date'),f('contractEnd','Contract end date','date'),f('lessons','Lessons learnt','textarea'),f('actions','Improvement actions','textarea')]},
  competitors:{label:'Competitors',single:false,roles:['BD Executive','Bid Manager'],fields:[f('name','Competitor name','text',null,true),f('type','Competitor type','select','CompType'),f('quotedPrice','Competitor bid price','number'),f('rank','Rank','select','Rank'),f('outcome','Competitor outcome','select','CompOutcome'),f('source','Information source','select','InfoSource'),f('strengths','Strengths','textarea'),f('weaknesses','Weaknesses','textarea'),f('notes','Intelligence notes','textarea')]}
};
export const SECTION_LABELS={S00:'Main details',S01:'Tender reference & client',S02:'Project location',S03:'Source & procurement',S04:'Dates & deadlines',S05:'Commercial & financial terms',S06:'Eligibility',S07:'Documents',S08:'Decision & ownership'};
export const DEFAULT_SETTINGS={urgentDays:7,criticalDays:3,dangerHours:24,finalHours:6,instrumentReminderDays:14,reminderOffsets:[10080,4320,1440,360],timezone:'Asia/Kolkata',requiredRegistrationFields:['tenderId','title','client','clientRef','clientType','sector','businessUnit','publishDate','deadline','submissionTime','validityDays','currency','estimatedValue','durationMonths','emdAmount','emdForm','source','tenderType','owner','priority','goDecision','region','location','portalUrl','queryDeadline','meetingDate','visitDate','technicalOpening','documentFee','performanceSecurity','turnoverRequired','experienceRequired','jvAllowed','eligibility'],requireDocuments:true,scoreWeights:{strategicFit:20,eligibilityScore:20,technicalCapability:20,financialCapacity:15,competitiveness:15,riskScore:10},scoreGo:70,scoreHold:50,notificationRecipients:{10080:['Bid Manager'],4320:['Bid Manager','BU Head'],1440:['Bid Manager','BU Head','Document Controller'],360:['Bid Manager','BU Head']},approvers:{scorecard:['Bid Committee / Director'],submission:['BU Head'],award:['BU Head'],unlock:['BU Head'],checklist:['Bid Manager'],registration:['BU Head']},permissions:{}};
export function permitted(user,module,action='write',settings=DEFAULT_SETTINGS){
 if(user?.roles?.includes('System Administrator'))return true;
 const overrides=settings.permissions?.[module]?.[action];
 const roles=overrides||(action==='approve'?settings.approvers?.[module]||MODULES[module]?.approvers:MODULES[module]?.roles)||(module==='documents'?['BD Executive','Document Controller']:module==='overview'||module==='registration'?['BD Executive','Bid Manager']:[]);
 return roles.some(r=>user?.roles?.includes(r));
}
export const pricingFields=['costEstimate','quotedPrice','margin','negotiatedPrice'];
export const canSeePricing=user=>user?.roles?.some(r=>['System Administrator','Bid Manager','Estimation','BU Head','Bid Committee / Director'].includes(r));
export function deadlineUtc(data){if(!data.deadline)return null;const time=data.submissionTime||'23:59';const date=new Date(`${data.deadline}T${time}:00Z`);const zone=data.timezone||'Asia/Kolkata';let utc=date.getTime();for(let i=0;i<3;i++){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(new Date(utc));const p=Object.fromEntries(parts.map(x=>[x.type,x.value]));const local=Date.UTC(+p.year,+p.month-1,+p.day,+p.hour,+p.minute,+p.second);utc+=date.getTime()-local;}return new Date(utc);}
export function classify(tender,records=[],settings=DEFAULT_SETTINGS,now=new Date()){
 const d=tender.data||tender;const sub=records.find(r=>r.module==='submission')?.data||{};const evaluation=records.find(r=>r.module==='evaluation')?.data||{};const award=records.find(r=>r.module==='award')?.data||{};
 const deadline=deadlineUtc(d);const diff=deadline?(deadline-now)/86400000:null;
 const submitted=sub.status==='Submitted'||!!sub.actualSubmission||!!sub.submittedAt;
 const withdrawn=sub.status==='Withdrawn'||award.approvalStatus==='Approved'&&award.outcome==='Withdrawn by Us';
 let status='Pending',reason='',appliedStatus='',awardCategory='',notAllottedReason='';
 if(submitted){status='Applied';appliedStatus=withdrawn?'Withdrawn after Submission':'Submitted';const outcome=award.approvalStatus==='Approved'?award.outcome:null;awardCategory=withdrawn?'Not Allotted':outcome==='Awarded to Us'?'Allotted':!outcome||outcome==='Awaiting Decision'?'Awaiting Result':'Not Allotted';notAllottedReason=withdrawn?'Withdrawn after Submission':awardCategory==='Not Allotted'?outcome:'';}
 else if(d.goDecision==='No-Go')reason='No-Go Decision';else if(d.pipelineStatus==='Cancelled by Client')reason='Cancelled by Client';else if(withdrawn)reason='Withdrawn before Submission';else if(diff!==null&&diff<0)reason='Deadline Missed';
 if(reason)status='Not Applied';
 const deadlineAlert=diff===null?'No deadline':diff<0?'Deadline Passed':diff<=settings.criticalDays?'Critical':diff<=settings.urgentDays?'Urgent':'On Track';
 const docs=records.filter(r=>r.module==='documents');const required=d.requiredDocumentKeys||['AV','AW','AX','AY','AZ','BA','BB','BD','BE'];const completeness=required.length?Math.round(required.filter(k=>docs.some(r=>r.data.type===k)).length/required.length*100):100;
 const checklist=records.filter(r=>r.module==='checklist'&&r.data.mandatory==='Yes');
 const pendingStage=d.goDecision!=='Go'?'Go / No-Go Review':completeness<100?'Document Collection':!records.some(r=>r.module==='instruments')&&Number(d.emdAmount)>0?'EMD / BG Arrangement':checklist.some(r=>r.data.status!=='Completed')?'Submission Checklist':sub.status==='Approved for Submission'?'Ready for Submission':'Bid Preparation';
 const actual=sub.actualSubmission?new Date(sub.actualSubmission):sub.submittedAt?new Date(sub.submittedAt):null;
 const decisionRecord=records.find(r=>r.module==='scorecard')?.data||{};return {score:decisionRecord.score??null,recommendation:decisionRecord.recommendation||'',status,notAppliedReason:reason,appliedStatus,awardCategory,notAllottedReason,deadlineUtc:deadline?.toISOString(),daysRemaining:diff,deadlineAlert,pendingStage,documentCompleteness:completeness,submittedOnTime:actual&&deadline?(actual<=deadline?'On Time':'Late'):'',evaluationStage:evaluation.stage||'',weightedValue:Number(d.estimatedValue||0)*Number(d.winProbability||0)/100,corrigendumCount:records.filter(r=>r.module==='corrigenda').length};
}
export function scorecard(data,settings){const w=settings.scoreWeights;const total=Object.values(w).reduce((a,b)=>a+Number(b),0);const score=total?Object.entries(w).reduce((sum,[k,v])=>sum+Number(data[k]||0)/5*Number(v),0)/total*100:0;return {score:Math.round(score*10)/10,recommendation:score>=settings.scoreGo?'GO':score>=settings.scoreHold?'HOLD':'NO-GO'};}
